project_id = "bqtpxmnsycxatmyjjtcx"

[functions.fetch-jira-issues]
verify_jwt = false

[functions.fetch-tempo-worklogs]
verify_jwt = false

[functions.test-jira-connection]
verify_jwt = false

[functions.invite-user]
verify_jwt = false
